// Define metadata for the document head
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// RootLayout - Define the main layout component wrapping all pages
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Render page content */}
        {children}
      </body>
    </html>
  );
}
